baseurl = "/"
languageCode = "en-us"
title = "Trunk Based Development"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-24415524-3"

[params]
	# General information
	author = "paul-hammant"
	description = "A portal on this practice"
	copyright = "TrunkBasedDevelopment.com's contributors."

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/paul-hammant/tbd"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue"
    	accent  = "light-blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "paul-hammant"
	email   = "paul@hammant.org"

[[menu.main]]
	name   = "Introduction"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Context"
	url    = "context/"
	weight = 5

[[menu.main]]
	name   = "Five minute overview"
	url    = "5-min-overview/"
	weight = 10

[[menu.main]]
	name   = "Deciding factors"
	url    = "deciding-factors/"
	weight = 20

[[menu.main]]
	name   = "VCS choices"
	url    = "vcs-choices/"
	weight = 30

[[menu.main]]
	name   = "Feature flags"
	url    = "feature-flags/"
	weight = 40

[[menu.main]]
	name   = "Branch by Abstraction"
	url    = "branch-by-abstraction/"
	weight = 53

[[menu.main]]
	name   = "Branch for release"
	url    = "branch-for-release/"
	weight = 55

[[menu.main]]
	name   = "Strangulation"
	url    = "strangulation/"
	weight = 57

[[menu.main]]
	name   = "Continuous Integration"
	url    = "continuous-integration/"
	weight = 60

[[menu.main]]
	name   = "Continuous Delivery"
	url    = "continuous-delivery/"
	weight = 70

[[menu.main]]
	name   = "Observed habits"
	url    = "observed-habits/"
	weight = 80

[[menu.main]]
	name   = "Doing it wrong"
	url    = "youre-doing-it-wrong/"
	weight = 90

[[menu.main]]
	name   = "Alternative branching models"
	url    = "alternative-branching-models/"
	weight = 100

[[menu.main]]
	name   = "Monorepos"
	url    = "monorepos/"
	weight = 110

[[menu.main]]
	name   = "Publications"
	url    = "publications/"
	weight = 120

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
