baseurl = "/"
languageCode = "en-us"
title = "Trunk Based Development"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-24415524-3"

[params]
	# General information
	author = "paul-hammant"
	description = "A material design theme for documentations."
	copyright = "Contributors to TrunkBasedDevelopment.com"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/paul-hammant/tbd"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue"
    	accent  = "light-blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "paul-hammant"
	email   = "paul@hammant.org"


[[menu.main]]
	name   = "Introduction"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Five minute overview"
	url    = "5-min-overview/"
	weight = 10

[[menu.main]]
	name   = "Branch By Abstraction"
	url    = "branch-by-abstraction/"
	weight = 15

[[menu.main]]
	name   = "Feature Flags"
	url    = "feature-flags/"
	weight = 20


[[menu.main]]
	name   = "Continuous Integration"
	url    = "continuous-integration/"
	weight = 25

[[menu.main]]
	name   = "Continuous Delivery"
	url    = "continuous-delivery/"
	weight = 30

[[menu.main]]
	name   = "Monorepos"
	url    = "monorepos/"
	weight = 35

[[menu.main]]
	name   = "Deciding Factors"
	url    = "deciding-factors/"
	weight = 40

[[menu.main]]
	name   = "VCS Choices"
	url    = "vcs-choices/"
	weight = 45

[[menu.main]]
	name   = "Doing It Wrong"
	url    = "you're doing-it-wrong/"
	weight = 50

[[menu.main]]
	name   = "Opposing Models"
	url    = "opposing-models/"
	weight = 55

[[menu.main]]
	name   = "Publications"
	url    = "publications/"
	weight = 60

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
